# make lumberjacklogger nil to not log to file
lumberjacklogger:
  filename: ./tmp.log
  maxage: 30 # days
  maxbackups: 0
  maxsize: 5 # megabytes
subreddits:
  - destination: ./tmp/grabbit
    limit: 1
    name: earthporn
    timeframe: day
  - destination: ./tmp/grabbit
    limit: 1
    name: cityporn
    timeframe: day
version: 2.0.0
