version: 2.0.0
# make lumberjacklogger nil to not log to file
lumberjacklogger:
  filename: ./tmp.log
  maxsize: 5  # megabytes
  maxbackups: 0
  maxage: 30  # days
subreddits:
  - name: earthporn
    destination: ./tmp/grabbit
    timeframe: "day"
    limit: 1
  - name: cityporn
    destination: ./tmp/grabbit
    timeframe: "day"
    limit: 1
